workflow:
  rules:
    # Don't run simple push pipelines
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    # Allow to interrupt pipelines on merge request if a new commit arrives
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      auto_cancel:
        on_new_commit: interruptible
    # Do not interrupt pipelines on main
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      auto_cancel:
        on_new_commit: none

# Suppress certain warnings
variables:
  PIPENV_VERBOSITY: -1

stages:
  - test

formatting:
  stage: test
  tags:
    - test
  script:
    # Use black to verify the correct formatting of all files
    - black --check .
  interruptible: true

py_test:
  stage: test
  tags:
    - test
  script:
    # Use most recent version from Pipfile
    - pipenv sync
    # Run all unit tests
    #- pipenv run python -m unittest discover system/tests/
    # Run all unit tests with coverage
    - pipenv run coverage run -m unittest discover system/tests/
    - pipenv run coverage html
  interruptible: true
  artifacts:
    paths:
      - htmlcov/*


ipynb_test:
  stage: test
  tags:
    - test
  script:
    # Use most recent version from Pipfile
    - pipenv sync
    # Convert all jupyter notebooks into python files
    - pipenv run jupyter nbconvert --to script *.ipynb
    # Run all notebooks
    - for file in *.py; do pipenv run ipython "$file"; done
  interruptible: true


stats_and_linting:
  stage: test
  tags:
    - test
  script:
    # count lines of code for each py and ipynb file, plus the sum:
    - find . \( -iname \*.ipynb -o -iname \*.py \) -not -path "*venv*" -print0 | xargs -0 wc -l > LOC.txt
    # Use most recent version from Pipfile, required for pylint and nbqa
    - pipenv sync
    # show pylint output of code for each py file:
    - find . -iname \*.py -not -path "*venv*" -print0 | xargs -0 pylint --exit-zero > pylint_py.txt
    # show pylint output of code for each ipynb file:
    - find . -iname \*.ipynb -not -path "*venv*" -print0 | xargs -0 nbqa pylint --exit-zero > pylint_ipynb.txt
  artifacts:
    paths:
      - LOC.txt
      - pylint_py.txt
      - pylint_ipynb.txt
  interruptible: true

